export const products = [
  {
    name: "Açafrão",
    price: 1,
    picture: "/assets/products/acafrao.png",
    description: "",
  },
  {
    name: "Alho Granulado",
    price: 1,
    picture: "/assets/products/alho-granulado.png",
    description: "",
  },
  {
    name: "Bicarbonato de Sódio",
    price: 1,
    picture: "/assets/products/bicarbonato-de-sodio.png",
    description: "",
  },
  {
    name: "Boldo do Chile",
    price: 1,
    picture: "/assets/products/boldo-do-chile.png",
    description: "",
  },
  {
    name: "Capim Santo",
    price: 1,
    picture: "/assets/products/capim-santo.png",
    description: "",
  },
  {
    name: "Cebola Desidratada",
    price: 1,
    picture: "/assets/products/cebola-desidratada.png",
    description: "",
  },
  {
    name: "Cha Verde",
    price: 1,
    picture: "/assets/products/cha-verde.png",
    description: "",
  },
  {
    name: "Chimichurri",
    price: 1,
    picture: "/assets/products/chimichurri.png",
    description: "",
  },
  {
    name: "Colorau",
    price: 1,
    picture: "/assets/products/colorau.png",
    description: "",
  },
  {
    name: "Curry",
    price: 1,
    picture: "/assets/products/curry.png",
    description: "",
  },
  {
    name: "Dry Rub",
    price: 1,
    picture: "/assets/products/dry-rub.png",
    description: "",
  },
  {
    name: "Feijão Supremo",
    price: 1,
    picture: "/assets/products/feijao-supremo.png",
    description: "",
  },
  {
    name: "Lemon Ervas",
    price: 1,
    picture: "/assets/products/lemon-ervas.png",
    description: "",
  },
  {
    name: "Lemon Pepper",
    price: 1,
    picture: "/assets/products/lemon-pepper.png",
    description: "",
  },
  {
    name: "Oregano",
    price: 1,
    picture: "/assets/products/oregano.png",
    description: "",
  },
  {
    name: "Paprica Defumada",
    price: 1,
    picture: "/assets/products/paprica-defumada.png",
    description: "",
  },
  {
    name: "Pimenta do Reino",
    price: 1,
    picture: "/assets/products/pimenta-do-reino.png",
    description: "",
  },
  {
    name: "Sal Rosa do Himaláia",
    price: 1,
    picture: "/assets/products/sal-rosa-do-himalaia.png",
    description: "",
  },
  {
    name: "Tempero Baiano",
    price: 1,
    picture: "/assets/products/tempero-baiano.png",
    description: "",
  },
];
